name: Nightly-minute-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Call our API route
        run: |
          curl --location --request GET 'https://spotify-compilation-playlist.herokuapp.com/refresh_token'
          sleep 5
          curl --location --request GET 'https://spotify-compilation-playlist.herokuapp.com/pull_songs'
          sleep 15
          curl --location --request GET 'https://spotify-compilation-playlist.herokuapp.com/update_playlist'
          sleep 40
