name: Nightly-minute-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --location --request GET 'https://spotify-compilation-playlist.vercel.app/refresh_token'
          sleep 5
          curl --location --request GET 'https://spotify-compilation-playlist.vercel.app/pull_songs'
          sleep 10
          curl --location --request GET 'https://spotify-compilation-playlist.vercel.app/update_playlist'
